#!/bin/bash

HEIGHT_OF_TREE=$1
WIDTH_OF_SNOW=$2

if (( $# != 2 )); then
        echo "Для створення ялинки треба одночасно як висота дерева, так і шар снігу на ньому!" >&2
        exit 1
fi

if [ "$HEIGHT_OF_TREE" -le 0 ] || [ "$WIDTH_OF_SNOW" -le 0 ]; then
        echo "Висота дерева та шар снігу повинні бути більші за 0!" >&2
        exit 2
fi

if [ "$HEIGHT_OF_TREE" -lt 8 ] || [ "$WIDTH_OF_SNOW" -lt 7 ]; then
        echo "ПОМИЛКА! Неможливо побудувати ялинку!" >&2
        exit 3
fi

DIFFERENCE=$((HEIGHT_OF_TREE - WIDTH_OF_SNOW))

if [ "$DIFFERENCE" -ne 0 ] && [ "$DIFFERENCE" -ne 1 ] && [ "$DIFFERENCE" -ne 2 ]; then
        echo "ПОМИЛКА! Неможливо побудувати ялинку!" >&2
        exit 4
fi

if [ $((HEIGHT_OF_TREE % 2)) -ne 0 ] && [ $((WIDTH_OF_SNOW % 2)) -ne 0 ]; then
        if [ "$DIFFERENCE" -eq 0 ]; then
                    echo "ПОМИЛКА! Неможливо побудувати ялинку!" >&2
                    exit 5
        fi
fi


if [ $((HEIGHT_OF_TREE % 2)) -eq 0 ] && [ $((WIDTH_OF_SNOW % 2)) -eq 0 ]; then
        if [ $((HEIGHT_OF_TREE - WIDTH_OF_SNOW)) -eq 2 ]; then
                    echo  "ПОМИЛКА! Неможливо побудувати ялинку!" >&2
                    exit 6
        fi
fi


function show_pine_tree(){
        local spaces=$1
        local chars=$2
        local symbol=$3
        i=0
        while [ $i -lt $spaces ]; do
        echo -n " "
        ((i++))
        done

        j=0
        while [ $j -lt $chars ]; do
        echo -n "$symbol"
        ((j++))
        done
        echo
}

HEIGHT_OF_FIRST_TRIANGLE=$(((HEIGHT_OF_TREE - 2) / 2))
MAX_SNOW_OF_FIRST_TRIANGLE=$((WIDTH_OF_SNOW - 2))

CURRENT_SYMBOL="*"

for ((chars = 1; chars <= MAX_SNOW_OF_FIRST_TRIANGLE; chars+=2)); do
    spaces=$(( (WIDTH_OF_SNOW - chars) / 2 ))

    show_pine_tree $spaces $chars "$CURRENT_SYMBOL"

    if [ "$CURRENT_SYMBOL" == "*" ]; then
        CURRENT_SYMBOL="#"
    else
        CURRENT_SYMBOL="*"
    fi
done

if [ "$CURRENT_SYMBOL" == "*" ]; then
    CURRENT_SYMBOL="#"
else
    CURRENT_SYMBOL="*"
fi


#Друга половина
for ((chars = 3; chars <= MAX_SNOW_OF_FIRST_TRIANGLE; chars+=2)); do
    spaces=$(( (WIDTH_OF_SNOW - chars) / 2 ))

    if [ "$CURRENT_SYMBOL" == "*" ]; then
        CURRENT_SYMBOL="#"
    else
        CURRENT_SYMBOL="*"
    fi

    show_pine_tree $spaces $chars "$CURRENT_SYMBOL"

done

for i in {1..2}; do
        spaces=$(( (WIDTH_OF_SNOW - 3) / 2 ))
        show_pine_tree $spaces 3 "#"
done

j=0

if [ $((WIDTH_OF_SNOW % 2)) -eq 0 ]; then
        WIDTH_OF_SNOW=$((WIDTH_OF_SNOW - 1))
fi

until [ $j -ge $WIDTH_OF_SNOW ]; do
        echo -n "*"
        ((j++))
done
echo
